### ISSUE TITLE
Spaces list/new

### ISSUE THREAD

**Issue by souljuse** [tadasmajeris/BNB#2]
1. '/spaces' - LIST OF SPACES
2. '/spaces/new' - add a space
3. '/spaces/:id' - book a space (calendar)

**Comment by tadasmajeris** [comment]
bug with Datepicker. make it choose in English format dd/mm/yyyy

DONE

**Comment by tadasmajeris** [comment]
available_to        shouldn't be before       available_from

**Comment by tadasmajeris** [comment]
entered data should stay in the form, when wrong details entered

DONE

**Comment by tadasmajeris** [comment]
dates cant be in the past
